package com.migapro.projecteuler.problems;

/**
 * Problem 002
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * @author Miga
 *
 */
public class Problem002 extends Problem {

	@Override
	public int solve() {
		int sum = 0;
		int n1 = 0;
		int n2 = 1;
		int fibo = 0;
		
		while (fibo < 4000000) {
			fibo = n1 + n2;
			n1 = n2;
			n2 = fibo;
			
			if (fibo % 2 == 0)
				sum += fibo;
		}
		
		return sum;
	}

}
